blog/urls.py
from django.urls import path
from . import views
from blog.views import pageNotFound

urlpatterns = [
    path('', views.BlogHome.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('post/<slug:post_slug>/edit/', views.edit_post, name='edit_post'),
    path('post/<slug:post_slug>/delete/', views.delete_post, name='delete_post'),
    path('category/<slug:cat_slug>/', views.WomenCategory.as_view(), name='category'),
    path('add_comment/<slug:post_slug>/', views.add_comment, name='add_comment'),
    path('add_like/<slug:post_slug>/', views.add_like, name='add_like'),
    path('post/<slug:post_slug>/like_comment/<int:comment_id>/', views.add_like_comment, name='add_like_comment'),
    path('post/<slug:post_slug>/edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('post/<slug:post_slug>/delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('soon/', views.soon_page, name='soon_page'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', views.UserProfile.as_view(), name='user_profile'),
]

coolsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include 

from coolsite import settings
from blog.views import pageNotFound 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')), 
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True, default='avatars/default_avatar.png')

    def get_absolute_url(self):
        return reverse('user_profile', kwargs={'username': self.username})

    class Meta:
        verbose_name = 'Користувач'
        verbose_name_plural = 'Користувачі'

@receiver(post_save, sender=CustomUser)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    if hasattr(instance, 'profile'):
        instance.profile.save()

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)

    def __str__(self):
        return f'Профіль користувача {self.user.username}'

class Blog(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(blank=True, verbose_name="Текст статті")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото", blank=True, null=True)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Час створення")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Час оновлення")
    is_published = models.BooleanField(default=True, verbose_name="Публікація")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name="Категорія")
    author = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='posts', verbose_name="Автор", null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    class Meta:
        verbose_name = 'Запис блогу'
        verbose_name_plural = 'Записи блогу'
        ordering = ['id']

class Comment(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments', verbose_name="Запис блогу")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Користувач")
    content = models.TextField(verbose_name="Коментар")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Час створення")
    likes = models.ManyToManyField(CustomUser, related_name='liked_comments', blank=True, verbose_name="Лайки на коментарі")

    def __str__(self):
        return f'Коментар від {self.user} до {self.post.title}'

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        ordering = ['created_at']

class Like(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='likes')

    class Meta:
        unique_together = ('post', 'user')
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Назва категорії")
    slug = models.SlugField(max_length=255, unique=True, verbose_name="URL")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'
        ordering = ['id']

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from .models import Blog, Comment, CustomUser, Profile

class AddPostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = "Категорія не обрана"

    class Meta:
        model = Blog
        fields = ['title', 'slug', 'content', 'photo', 'is_published', 'cat']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise forms.ValidationError('Довжина перевищує 200 символів')
        return title

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    first_name = forms.CharField(label="Ім'я", widget=forms.TextInput(attrs={'class': 'form-input'}))
    last_name = forms.CharField(label='Прізвище', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-input'
        self.fields['password1'].widget.attrs['class'] = 'form-input'
        self.fields['password2'].widget.attrs['class'] = 'form-input'

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }

class EditProfileForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'avatar')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.mail import send_mail, BadHeaderError
from .forms import ContactForm, AddPostForm, RegisterUserForm, LoginUserForm, CommentForm, EditProfileForm
from .models import *
from .utils import menu
from django.http import JsonResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.dispatch import receiver
from django.db.models.signals import post_save

class BlogHome(ListView):
    model = Blog
    template_name = 'index.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = {'title': "Головна сторінка"}
        context.update(c_def)
        context.update(menu(self.request))
        return context

    def get_queryset(self):
        return Blog.objects.filter(is_published=True).select_related('cat')

def about(request):
    contact_list = Blog.objects.all()
    paginator = Paginator(contact_list, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'about.html', {'page_obj': page_obj, 'menu': menu(request), 'title': 'Про сайт'})

class AddPage(LoginRequiredMixin, CreateView):
    form_class = AddPostForm
    template_name = 'addpage.html'
    login_url = reverse_lazy('login')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['admin@example.com']
            if cc_myself:
                recipients.append(sender)

            try:
                send_mail(subject, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('home')
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form, 'menu': menu(request), 'title': 'Зворотній зв\'язок'})

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'

    def get_success_url(self):
        return reverse_lazy('home')

def logout_user(request):
    logout(request)
    return redirect('login')

class ShowPost(DetailView):
    model = Blog
    template_name = 'post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.select_related('user')
        context['form'] = CommentForm()
        return context

class WomenCategory(ListView):
    model = Blog
    template_name = 'index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_queryset(self):
        return Blog.objects.filter(cat__slug=self.kwargs['cat_slug'], is_published=True).select_related('cat')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = {'title': 'Категорія - ' + str(context['posts'][0].cat), 'cat_selected': context['posts'][0].cat_id}
        context.update(c_def)
        context.update(menu(self.request))
        return context

@login_required
def add_like(request, post_slug):
    post = get_object_or_404(Blog, slug=post_slug)
    Like.objects.get_or_create(post=post, user=request.user)
    return redirect(post.get_absolute_url())

@login_required
def add_like_comment(request, post_slug, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, post__slug=post_slug)
    comment.likes.add(request.user)
    return redirect(comment.post.get_absolute_url())

@login_required
def edit_comment(request, post_slug, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, post__slug=post_slug, user=request.user)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect(comment.post.get_absolute_url())
    else:
        form = CommentForm(instance=comment)
    return render(request, 'edit_comment.html', {'form': form, 'post': comment.post})

@login_required
def delete_comment(request, post_slug, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, post__slug=post_slug, user=request.user)
    if request.method == 'POST':
        comment.delete()
        return redirect(comment.post.get_absolute_url())
    return render(request, 'delete_comment.html', {'comment': comment})

@login_required
def soon_page(request):
    return render(request, 'soon.html', {'menu': menu(request), 'title': 'Скоро'})

@login_required
def profile(request):
    return render(request, 'profile.html', {'menu': menu(request), 'title': 'Профіль'})

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            if hasattr(request.user, 'profile'):
                if 'avatar' in request.FILES:
                    request.user.profile.avatar = request.FILES['avatar']
                    request.user.profile.save()
            return redirect('profile')
    else:
        form = EditProfileForm(instance=request.user)
    return render(request, 'edit_profile.html', {'form': form, 'menu': menu(request), 'title': 'Редагувати профіль'})


class UserProfile(DetailView):
    model = CustomUser
    template_name = 'profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    context_object_name = 'user_profile'

def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Сторінку не знайдено</h1>')

@login_required
def add_comment(request, post_slug):
    post = get_object_or_404(Blog, slug=post_slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect(post.get_absolute_url())
    else:
        form = CommentForm()
    return render(request, 'add_comment.html', {'form': form, 'post': post})

@login_required
def edit_post(request, post_slug):
    post = get_object_or_404(Blog, slug=post_slug)
    if request.user == post.author or request.user.is_staff:
        if request.method == 'POST':
            form = AddPostForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                return redirect(post.get_absolute_url())
        else:
            form = AddPostForm(instance=post)
        return render(request, 'edit_post.html', {'form': form, 'post': post})
    else:
        return redirect('home')

@login_required
@staff_member_required
def delete_post(request, post_slug):
    post = get_object_or_404(Blog, slug=post_slug)
    if request.method == 'POST':
        post.delete()
        return redirect('home')
    return render(request, 'delete_post.html', {'post': post})

@receiver(post_save, sender=CustomUser)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    if hasattr(instance, 'profile'):
        instance.profile.save()

blog/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<p>Ласкаво просимо до нашого блогу, де ви можете знайти найостанніші статті, написані нашими талановитими авторами. Тут ви зможете переглядати статті за категоріями, тегами, залишати коментарі та оцінювати статті. Підпишіться на наші оновлення, щоб отримувати повідомлення про нові статті прямо на вашу електронну пошту.</p>
{% endblock %}

blog/templates/add_comment.html
{% for comment in post.comments.all %}
<div class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
        <p class="mb-1">{{ comment.content }}</p>
        <small class="text-muted">{{ comment.user.username }} - {{ comment.created_at }}</small>
    </div>
    <div>
        {% if request.user.is_authenticated %}
        <form method="post" action="{% url 'add_like_comment' post.slug comment.id %}" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger">
                {% if request.user in comment.likes.all %}
                    <i class="bi bi-heart-fill"></i>
                {% else %}
                    <i class="bi bi-heart"></i> 
                {% endif %}
            </button>
        </form>
        {% endif %}
        
        {% if comment.user == request.user %}
        <a href="{% url 'edit_comment' post.slug comment.id %}" class="btn btn-outline-secondary btn-sm">Редагувати</a>
        <form method="post" action="{% url 'delete_comment' post.slug comment.id %}" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-sm">Видалити</button>
        </form>
        {% endif %}
    </div>
</div>
{% empty %}
<div class="list-group-item">
    <p class="mb-1">Поки що немає коментарів.</p>
</div>
{% endfor %}

blog/templates/addpage.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>

<form action="{% url 'add_page' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Додати</button>
</form>

{% endblock %}

blog/templates/base.html
    {% load static %}
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>{{ title }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
    <table class="table-page" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td valign="top">
                {% block mainmenu %}
                <div class="header">
                    <ul id="mainmenu" class="mainmenu">
                        <li class="logo"><a href="{% url 'home' %}"><i class="bi bi-bootstrap"></i></a></li>
                        <li><a href="{% url 'about' %}">Про сайт</a></li>
                        <li><a href="{% url 'contact' %}">Зворотній зв'язок</a></li>
                        <li><a href="{% url 'add_page' %}">Додати статтю</a></li>
                        <li class="last">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'user_profile' request.user.username %}">{{ user.username }}</a> | <a href="{% url 'logout' %}">Вийти</a>
                            {% else %}
                                <a href="{% url 'register' %}">Реєстрація</a> | <a href="{% url 'login' %}">Увійти</a>
                            {% endif %}
                        </li>
                    </ul>
                    <div class="clear"></div>
                </div>
                {% endblock mainmenu %}
                
                <table class="table-content" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td valign="top" class="left-chapters">
                            <ul id="leftchapters">
                                {% if cat_selected == 0 %}
                                    <li class="selected">Усі категорії</li>
                                {% else %}
                                    <li><a href="{% url 'home' %}">Усі категорії</a></li>
                                {% endif %}
                                
                                {% for c in cats %}
                                    {% if c.num_posts > 0 %}
                                        {% if c.pk == cat_selected %}
                                            <li class="selected">{{ c.name }}</li>
                                        {% else %}
                                            <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </td>
                        <td valign="top" class="content">
                            {% block breadcrumbs %}
                            {% endblock %}
                            
                            <div class="content-text">
                                {% block content %}
                                {% endblock %}
                                {% if page_obj.has_other_pages %}
                                <nav class="list-pages">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                        <li class="page-num">
                                            <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                                        </li>
                                        {% endif %}
                                        
                                        {% for p in paginator.page_range %}
                                            {% if page_obj.number == p %}
                                            <li class="page-num page-num-selected">{{ p }}</li>
                                            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                                            <li class="page-num">
                                                <a href="?page={{ p }}">{{ p }}</a>
                                            </li>
                                            {% endif %}
                                        {% endfor %}
                                        
                                        {% if page_obj.has_next %}
                                        <li class="page-num">
                                            <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td valign="bottom">
                <div id="footer" style="text-align: center; padding: 20px 0;">
                    <p class="footer-text">&copy; Sandy Team</p>
                </div>
            </td>
        </tr>
    </table>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>

blog/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>

    <form method="post" class="mt-4">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label for="{{ form.subject.id_for_label }}" class="form-label">Тема:</label>
            {{ form.subject }}
            <div class="form-error">{{ form.subject.errors }}</div>
        </div>

        <div class="mb-3">
            <label for="{{ form.message.id_for_label }}" class="form-label">Повідомлення:</label>
            {{ form.message }}
            <div class="form-error">{{ form.message.errors }}</div>
        </div>

        <div class="mb-3">
            <label for="{{ form.sender.id_for_label }}" class="form-label">Ваша електронна пошта:</label>
            {{ form.sender }}
            <div class="form-error">{{ form.sender.errors }}</div>
        </div>

        <div class="mb-3 form-check">
            {{ form.cc_myself }}
            <label for="{{ form.cc_myself.id_for_label }}" class="form-check-label">Копіювати мені</label>
            <div class="form-error">{{ form.cc_myself.errors }}</div>
        </div>

        <button type="submit" class="btn btn-primary">Відправити</button>
    </form>
</div>
{% endblock %}

blog/templates/delete_comment.htm
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="mt-4">Видалити коментар</h1>
    <p>Ви впевнені, що хочете видалити цей коментар?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Видалити</button>
        <a href="{% url 'post' post.slug %}" class="btn btn-secondary">Відміна</a>
    </form>
</div>
{% endblock %}

blog/templates/delete_post.html
{% extends 'base.html' %}

{% block content %}
  <h1>Видалити статтю</h1>
  <p>Ви впевнені, що хочете видалити цю статтю?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Так, видалити</button>
    <a href="{% url 'post' post.slug %}">Скасувати</a>
  </form>
{% endblock %}

blog/templates/edit_post.html
{% extends 'base.html' %}

{% block content %}
  <h1>Редагувати статтю</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберегти</button>
  </form>
{% endblock %}

blog/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1>Редагування профілю</h1>
    <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_username" class="form-label">Ім'я користувача:</label>
            {{ form.username }}
            <div class="form-text">Обов'язкове поле. Не більше 150 символів. Тільки букви, цифри і символи @/./+/-/_.</div>
        </div>
        <div class="mb-3">
            <label for="id_first_name" class="form-label">Ім'я:</label>
            {{ form.first_name }}
        </div>
        <div class="mb-3">
            <label for="id_last_name" class="form-label">Прізвище:</label>
            {{ form.last_name }}
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label">Адреса електронної пошти:</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label for="id_avatar" class="form-label">Аватар:</label>
            {{ form.avatar }}
        </div>
        <button type="submit" class="btn btn-primary">Зберегти</button>
    </form>
</div>
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>

    <form method="post" class="mt-4">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>

        <div class="mb-3">
            <label class="form-label" for="id_username">Ім'я користувача:</label>
            {{ form.username }}
            <div class="form-error">{{ form.username.errors }}</div>
        </div>

        <div class="mb-3">
            <label class="form-label" for="id_password">Пароль:</label>
            {{ form.password }}
            <div class="form-error">{{ form.password.errors }}</div>
        </div>

        <button type="submit" class="btn btn-primary">Увійти</button>
    </form>

    <hr>
    <div class="text-center">
        <p>Або авторизуйтесь через:</p>
        <a href="{% url 'soon_page' %}" class="btn btn-dark">
            <i class="bi bi-google mx-1"></i> Google
        </a>
        <a href="{% url 'soon_page' %}" class="btn btn-dark">
            <i class="bi bi-facebook mx-1"></i> Facebook
        </a>
        <a href="{% url 'soon_page' %}" class="btn btn-dark">
            <i class="bi bi-github mx-1"></i> GitHub
        </a>
    </div>
</div>
{% endblock %}

blog/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1>Профіль користувача</h1>
    <div>
        {% if user.profile.avatar %}
    <img src="{{ user.profile.avatar.url }}" alt="Avatar" class="img-thumbnail" width="150" height="150">
{% else %}
    <img src="{% static 'default_avatar.png' %}" alt="Default Avatar" class="img-thumbnail" width="150" height="150">
{% endif %}
    </div>
    <p>Логін: {{ user.username }}</p>
    <p>Ім'я: {{ user.first_name }}</p>
    <p>Прізвище: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <a href="{% url 'edit_profile' %}">Редагувати профіль</a>
</div>
{% endblock %}

blog/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>{{ title }}</h1>

    <form method="post" class="mt-4">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="id_username" class="form-label">Логін:</label>
            {{ form.username }}
            <div class="form-error">{{ form.username.errors }}</div>
        </div>

        <div class="mb-3">
            <label for="id_email" class="form-label">Email:</label>
            {{ form.email }}
            <div class="form-error">{{ form.email.errors }}</div>
        </div>

        <div class="mb-3">
            <label for="id_password1" class="form-label">Пароль:</label>
            {{ form.password1 }}
            <div class="form-error">{{ form.password1.errors }}</div>
        </div>

        <div class="mb-3">
            <label for="id_password2" class="form-label">Підтвердження пароля:</label>
            {{ form.password2 }}
            <div class="form-error">{{ form.password2.errors }}</div>
        </div>

        <div class="mb-3">
            <label for="id_first_name" class="form-label">Ім'я:</label>
            {{ form.first_name }}
            <div class="form-error">{{ form.first_name.errors }}</div>
        </div>

        <div class="mb-3">
            <label for="id_last_name" class="form-label">Прізвище:</label>
            {{ form.last_name }}
            <div class="form-error">{{ form.last_name.errors }}</div>
        </div>

        <button type="submit" class="btn btn-primary">Реєстрація</button>
    </form>
</div>
{% endblock %}